name: warbuilder
description: WarBuilder Project

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
