name: warbuilder
description: WarBuilder Project

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  bloc: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fluent_ui: ^4.1.1
  fluentui_system_icons: ^1.1.189
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
